### ISSUE TITLE
Reversed order of effects?

### ISSUE THREAD

**Issue by akovari** [ccapndave/elm-effects-extra#1]
Shouldn't it return `Effects.batch [ effects, effects' ]` instead of `Effects.batch [ effects', effects ]` in `pipeUpdate`. Why the reversed order?

**Comment by akovari** [comment]
Well, never mind probably. I thought this was causing some of my problems but I was wrong. I guess it doesn't matter.

**Comment by ccapndave** [comment]
I'm not sure if Elm makes any guarantees about whether the order of effects in the batch makes any difference, but you are quite right; there isn't any reason to change them around.  This library has actually been replaced with https://github.com/ccapndave/elm-update-extra so I'll make the change there.
